const FETCH_GAMES = "FETCH_GAMES";
const FETCH_GENRES = "FETCH_GENRES";
const POST_GAMES = "POST_GAMES";
const FETCH_PLATFORMS = "FETCH_PLATFORMS";
const SORT_ALPHABETICAL = "SORT_ALPHABETICAL";
const RESET = "RESET";
const FETCH_DB_GAMES = "FETCH_DB_GAMES";
const FILTER_GENRES = "FILTER_GENRES";
const GET_NAME = "GET_NAME";
const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export {
	FETCH_GAMES,
	FETCH_GENRES,
	POST_GAMES,
	FETCH_PLATFORMS,
	SORT_ALPHABETICAL,
	RESET,
	FETCH_DB_GAMES,
	FILTER_GENRES,
	GET_NAME,
	TOGGLE_SIDEBAR,
};
